"""Load modsweep.toml - the authoritative record of active sources.

The config is the durable statement of which lists are active: retiring a
list means removing its line and rerunning `report`/`sweep`. Source types are
declared explicitly (wabbajack / nolvus / installs / recovery) so nothing is
auto-detected from a config entry - important for setups where installs are
spread across drives or live next to unrelated folders. CLI arguments
override config values. Relative paths resolve against the config file's
directory.
"""

from __future__ import annotations

import json
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_NAME = "modsweep.toml"


@dataclass
class Config:
    downloads: Path | None = None
    cache: Path | None = None
    wabbajack: list[Path] = field(default_factory=list)  # files or dirs to search
    nolvus: list[Path] = field(default_factory=list)  # InstallPackage.xml files
    installs: list[Path] = field(default_factory=list)  # MO2 installs -> [NoDelete]
    recovery: list[Path] = field(default_factory=list)  # installs whitelisted whole
    snapshots: list[Path] = field(default_factory=list)  # exported snapshot JSONs
    exclude: list[str] = field(default_factory=list)  # globs vs label or file name
    latest_only: bool = False  # keep only the newest version of each list
    quarantine: Path | None = None
    quarantine_keep_days: int | None = None  # purge batches older than this

    @property
    def has_sources(self) -> bool:
        return bool(
            self.wabbajack or self.nolvus or self.installs or self.recovery or self.snapshots
        )


def load(path: Path | None) -> Config:
    """Load config from `path`, or ./modsweep.toml if present, else empty."""
    if path is None:
        path = Path(DEFAULT_NAME)
        if not path.exists():
            return Config()
    elif not path.exists():
        raise SystemExit(f"error: config not found: {path}")

    data = tomllib.loads(path.read_text(encoding="utf-8"))
    base = path.resolve().parent

    def resolve(value: str) -> Path:
        p = Path(value)
        return p if p.is_absolute() else base / p

    def resolve_list(key: str, keep_keywords: bool = False) -> list[Path]:
        out: list[Path] = []
        for v in data.get(key, []):
            if keep_keywords and str(v).strip().lower() == "bundled":
                # sentinel: expanded at resolution time (package + user
                # manifest dirs), preserved verbatim through save/load
                out.append(Path("bundled"))
            else:
                out.append(resolve(v))
        return out

    quarantine_data = data.get("quarantine") or {}
    quarantine = quarantine_data.get("dir")
    keep_days = quarantine_data.get("keep_days")
    return Config(
        downloads=resolve(data["downloads"]) if "downloads" in data else None,
        cache=resolve(data["cache"]) if "cache" in data else None,
        wabbajack=resolve_list("wabbajack"),
        nolvus=resolve_list("nolvus", keep_keywords=True),
        installs=resolve_list("installs"),
        recovery=resolve_list("recovery"),
        snapshots=resolve_list("snapshots"),
        exclude=[str(v) for v in data.get("exclude", [])],
        latest_only=bool(data.get("latest_only", False)),
        quarantine=resolve(quarantine) if quarantine else None,
        quarantine_keep_days=int(keep_days) if keep_days is not None else None,
    )


def save(cfg: Config, path: Path) -> None:
    """Write the config as documented TOML.

    Comments are regenerated on every save (the GUI editor owns the file
    once it manages it) and paths are written as given - the editor supplies
    absolute paths from its pickers.
    """
    lines = [
        "# modsweep.toml - the record of active sources of truth.",
        "# Generated by the modsweep config editor; comments are regenerated",
        "# on save. CLI flags override these values.",
        "",
    ]
    if cfg.downloads is not None:
        lines.append(f"downloads = {_toml_str(cfg.downloads)}")
    if cfg.cache is not None:
        lines.append(f"cache = {_toml_str(cfg.cache)}")
    lines.append(f"latest_only = {'true' if cfg.latest_only else 'false'}")
    for key, values, comment in (
        ("wabbajack", cfg.wabbajack,
         ".wabbajack files, or directories searched recursively for them"),
        ("nolvus", cfg.nolvus,
         "InstallPackage .xml/.xml.gz files, or directories of them"),
        ("installs", cfg.installs,
         "MO2 installs checked for [NoDelete] custom additions"),
        ("recovery", cfg.recovery,
         "installs whitelisted whole, by archive NAME only"),
        ("snapshots", cfg.snapshots,
         "snapshot JSONs exported by `modsweep snapshot`"),
    ):
        lines += ["", f"# {comment}", _toml_list(key, values)]
    lines += [
        "",
        "# retire lists: globs matched against the label or manifest file name",
        _toml_list("exclude", cfg.exclude),
    ]
    if cfg.quarantine is not None or cfg.quarantine_keep_days is not None:
        lines += ["", "[quarantine]"]
        if cfg.quarantine is not None:
            lines.append(f"dir = {_toml_str(cfg.quarantine)}")
        if cfg.quarantine_keep_days is not None:
            lines.append(f"keep_days = {cfg.quarantine_keep_days}")
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def _toml_str(value: object) -> str:
    text = str(value)
    if "'" not in text:
        return f"'{text}'"  # literal string: no backslash escaping needed
    return json.dumps(text)  # JSON escaping is valid TOML basic-string syntax


def _toml_list(key: str, values: list) -> str:
    if not values:
        return f"{key} = []"
    items = ",\n    ".join(_toml_str(v) for v in values)
    return f"{key} = [\n    {items},\n]"
